<?php

namespace common\modules\controllers;

use common\models\Answers;
use common\models\Questions;
use common\models\Tests;
use common\models\TestsSearch;
use common\models\User;
use Yii;
use yii\bootstrap\ActiveForm;
use yii\filters\AccessControl;
use yii\web\Controller;

/**
 * Default controller for the `test` module
 */
class IndexController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'edit', 'quiz', 'addquestionbool', 'addquestionfull', 'deletequestion', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        $test = Tests::find()->all();
        $filterModel = new TestsSearch();
        $dp = $filterModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'test' => $test,
            'dp' => $dp,
            'filterModel' => $filterModel
        ]);
    }

    public function actionCreate()
    {
        $test = new Tests();
        if ($test->load(Yii::$app->request->post()) && $test->validate()) {
            $test->save();
            return $this->redirect('edit?id=' . Yii::$app->db->getLastInsertID());
        }

        return $this->render('create', [
            'test' => $test,
        ]);
    }

    public function beforeAction($action)
    {
        $user_role = Yii::$app->session->get('role');
        // if user is teacher then allows to create tests
        // for frontend and backend
        if ($user_role == User::ROLE_STUDENT) {
            $this->goHome();
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionEdit()
    {

        $id = Yii::$app->request->get('id');
        $id = intval($id);
        $test = Tests::find()->where(['id' => $id])->one();

        $question = new Questions();
        if ($question->load(Yii::$app->request->post()) && $question->validate()) {
            $question->test_id = $id;
            $question->save();
        }

        return $this->render('edit', [
            'test' => $test,
        ]);
    }

    public function actionDeletequestion($id = null, $test_id = null)
    {
        if (!empty($test_id)) {
            if (empty($id = intval($id))) {
                return $this->redirect('/test/index/edit?id=' . $test_id);
            } else {
                Questions::deleteAll(['id' => $id]);
                return $this->redirect('/test/index/edit?id=' . $test_id);
            }
        }

        return $this->redirect('/test');
    }

    public function actionAddquestionbool($id = null)
    {
        $test_id = intval($id);

        if (empty($test_id))
            return $this->redirect('/test/');

        $post = Yii::$app->request->post();
        if (!empty($post)) {
            $question = new Questions();
            $answer1 = new Answers();
            $answer2 = new Answers();

            $question->test_id = $test_id;
            $question->text = $post['Questions']['text'];
            $question->save();

            $question_id = Yii::$app->db->lastInsertID;

            $answer1->question_id = $question_id;
            $answer1->text = $post['Answers'][1]['text'];
            $answer1->isCorrect = intval($post['Answers'][1]['isCorrect']);

            $answer2->question_id = $question_id;
            $answer2->text = $post['Answers'][2]['text'];
            $answer2->isCorrect = intval($post['Answers'][2]['isCorrect']);

            $answer1->save();
            $answer2->save();

            return $this->redirect('/test/index/edit?id=' . $test_id);
        }
        return $this->render('addquestionbool', [
            'question' => new Questions(),
            'answer1' => new Answers(),
            'answer2' => new Answers(),
        ]);
    }

    public function actionAddquestionfull($id = null)
    {
        $test_id = intval($id);

        if (empty($test_id))
            return $this->redirect('/test/');

        $post = Yii::$app->request->post();
        if (!empty($post)) {
            $question = new Questions();
            $answer1 = new Answers();
            $answer2 = new Answers();
            $answer3 = new Answers();
            $answer4 = new Answers();

            $question->test_id = $test_id;
            $question->text = $post['Questions']['text'];
            $question->save();

            $question_id = Yii::$app->db->lastInsertID;

            $answer1->question_id = $question_id;
            $answer1->text = $post['Answers'][1]['text'];
            $answer1->isCorrect = intval($post['Answers'][1]['isCorrect']);

            $answer2->question_id = $question_id;
            $answer2->text = $post['Answers'][2]['text'];
            $answer2->isCorrect = intval($post['Answers'][2]['isCorrect']);

            $answer3->question_id = $question_id;
            $answer3->text = $post['Answers'][3]['text'];
            $answer3->isCorrect = intval($post['Answers'][3]['isCorrect']);

            $answer4->question_id = $question_id;
            $answer4->text = $post['Answers'][4]['text'];
            $answer4->isCorrect = intval($post['Answers'][4]['isCorrect']);

            $answer1->save();
            $answer2->save();
            $answer3->save();
            $answer4->save();

            return $this->redirect('/test/index/edit?id=' . $test_id);
        }
        return $this->render('addquestionfull', [
            'question' => new Questions(),
            'answer1' => new Answers(),
            'answer2' => new Answers(),
            'answer3' => new Answers(),
            'answer4' => new Answers(),
        ]);
    }

    public function actionDelete($id = null)
    {
        if (!empty($id = intval($id))) {
            Tests::deleteAll(['id' => $id]);
            return $this->redirect('/test');
        }
        return $this->redirect('/test');
    }

    public function actionQuiz()
    {
        $id = Yii::$app->request->get('id');
        $id = intval($id);
        $test = Tests::find()->where(['id' => $id])->one();

        return $this->render('quiz', [
            'test' => $test,

        ]);
    }

}
